### PR TITLE
[WIP] Bsve integration plugin

### PR DESCRIPTION
**Pull request by jbeezley**
@mgrauer I think this (along with https://github.com/Kitware/minerva/tree/bsve-config) does something like what you were asking for last week.  It adds the BSVE specific configuration into minerva's build.  For the moment, I just copied the bsve directory from your forbidden branch.

### CODE REVIEW

**Comment by mgrauer** [comment]
Thanks @jbeezley, this is very helpful.

At the time I was developing that branch, I needed to build GeoViz both as a BSVE 3rd party app (where we package up the client and push it to the BSVE, but the server comes from Docker) and also as a self contained client-server from Docker (the 3rd GeoViz tab in the BSVE works this way).

Going forward, I think we will only be deploying GeoViz via the 3rd GeoViz tab, and will not need the BSVE packaging portion of it.  I'm a bit conflicted whether we should keep it here or not.

The upside is that we actually maintain a way to do it if we need to recapture it.  The downside is that it requires additional support in minerva (bsve-config branch additions) and could add confusion to the primary deployment story.

Apologies that I didn't explain this well enough before you did this work.  Do you have an opinion here?

**Comment by jbeezley** [comment]
If it isn't needed, we might as well just get rid of it.  I assume there is still a need for `bsve/configure.js` to do some sort of special build step for the BSVE deployment, correct?

**Comment by mgrauer** [comment]
Good question about `bsve/configure.js`--I'm not sure.  We can talk about the right approach in the meeting this afternoon.

When I deployed the GeoViz app, it used a top level mako template to generate the index doc in cherrypy, the same as in vanilla Minerva, so no statically generated index.html document in that case.

A problem in testing this outside of the BSVE (e.g., pointing a browser directly at minerva-beta.bsvecosystem.net) was that the BSVE JS was not loaded (minor problem) and that the main.js would error out b/c the BSVE object did not exist (major problem).

It would be great if we could come up with a way to run this from minerva-docker in a BSVE-embedded or BSVE-mocked mode for quicker development.

**Comment by mgrauer** [comment]
Also, I'm getting an error with the volume specification on this branch.

ERROR: for mongodb  Cannot create container for service mongodb: Invalid volume spec "db": Invalid volume destination path: 'db' mount path must be absolute.
ERROR: Encountered errors while bringing up the project.

docker --version
Docker version 1.12.1, build 23cf638
docker-compose --version
docker-compose version 1.8.0, build 94f7016

**Pull request closed without merging**
